# Generated by Django 4.2.14 on 2024-07-13 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyConverter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CZK", "Czech koruna"),
                            ("EUR", "Euro"),
                            ("PLN", "Polish zloty"),
                            ("USD", "US dollar"),
                        ],
                        max_length=3,
                        unique=True,
                        verbose_name="Short Name",
                    ),
                ),
                ("cur_to_usd", models.FloatField(verbose_name="Rate To USD")),
                ("created_date", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created Date")),
                ("updated_date", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Updated Date")),
            ],
            options={
                "verbose_name": "Rate To USD",
                "verbose_name_plural": "Rates To USD",
            },
        ),
    ]
